language: haskell
ghc:
  - 7.8

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3 cabal-install-1.20
  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:/opt/cabal/1.20/bin:$PATH
  - travis_retry cabal update
  - travis_retry cabal install Cabal

  - travis_retry sudo add-apt-repository -y ppa:chris-lea/node.js
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install nodejs
  - travis_retry sudo npm install -g bower grunt-cli
  - sudo chown -R `whoami` ~/.npm

  - travis_retry sudo apt-get install libnetcdf-dev netcdf-bin postgresql libpq-dev

install:
  - travis_retry cabal install --only-dependencies --enable-tests --reorder-goals

script:
  - createdb volare_test
  - echo "CREATE USER volare WITH ENCRYPTED PASSWORD 'password'" | psql -U postgres
  - cabal configure --enable-tests -fglibcxx && cabal build && cabal test
