language: haskell
ghc:
  - 7.6

install:
  - sudo apt-get install libnetcdf-dev netcdf-bin postgresql libpq-dev
  - createdb volare_test
  - cabal install alex
  - cabal install happy
  - cabal install --only-dependencies --enable-tests
  - echo "CREATE USER volare WITH ENCRYPTED PASSWORD 'password'" | psql -U postgres

script:
  - cabal configure --enable-tests -fglibcxx && cabal build && cabal test
