env:
  - CABALVER=1.22 GHCVER=7.10.2 ALEXVER=3.1.4 HAPPYVER=1.19.5

addons:
  - postgresql: "9.3"

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy-$HAPPYVER alex-$ALEXVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH
  - travis_retry cabal update
  - travis_retry cabal install Cabal

  - travis_retry sudo add-apt-repository -y ppa:chris-lea/node.js
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install nodejs
  - travis_retry sudo npm install -g bower grunt-cli
  - sudo chown -R `whoami` ~/.npm

  - travis_retry sudo apt-get install libnetcdf-dev netcdf-bin libpq-dev

install:
  - travis_retry cabal install --jobs --only-dependencies --enable-tests --reorder-goals

before_script:
  - createdb volare_test
  - echo "CREATE USER volare WITH ENCRYPTED PASSWORD 'password'" | psql -U postgres

script:
  - cabal configure --enable-tests -fglibcxx && cabal build && cabal test
