Default: &defaults
  user: volare
  password: password
  host: localhost
  poolsize: 10

Development:
  database: volare_development
  poolsize: 1
  <<: *defaults

Testing:
  database: volare_test
  <<: *defaults

Staging:
  database: volare_staging
  poolsize: 100
  <<: *defaults

Production:
  database: volare
  poolsize: 100
  <<: *defaults
